# Generated by Django 4.0.5 on 2022-06-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examName', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='exam/pdf/')),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
