# Generated by Django 4.0.5 on 2022-06-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examupl',
            name='pdf',
            field=models.FileField(upload_to='exam/updf/'),
        ),
    ]
